server:
  port: 8082

profile:
  datasource:
    connection:
      jdbc-url: jdbc:mysql://39.100.149.36:3306/javaDemo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456a
